"""Movie model

Revision ID: 48892b0f1e66
Revises: 93e30390d405
Create Date: 2025-09-16 19:35:39.764463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48892b0f1e66'
down_revision: Union[str, Sequence[str], None] = '93e30390d405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint(op.f('un_name'), 'students', type_='unique')
    op.create_unique_constraint('student_uq_id', 'students', ['id'])
    op.create_unique_constraint(None, 'students', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint('student_uq_id', 'students', type_='unique')
    op.create_unique_constraint(op.f('un_name'), 'students', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('students', 'id')
    # ### end Alembic commands ###
