"""Movie model

Revision ID: c6744bc10fc3
Revises: 960e1282db8f
Create Date: 2025-09-15 17:11:30.237618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6744bc10fc3'
down_revision: Union[str, Sequence[str], None] = '960e1282db8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_movie_title', 'movies', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_movie_title', 'movies', type_='unique')
    # ### end Alembic commands ###
